
version: '3'

services:
  profittrailer:
    build: .
    container_name: profittrailer
    volumes:
      - ./application.properties:/app/ProfitTrailer/application.properties
      - ./data:/app/ProfitTrailer/data
    restart: always
    ports:
      - "8081:8081"
